---Create User AccountAdmin ---
CREATE USER somdutta password = '12345' DEFAULT_ROLE = ACCOUNTADMIN MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE ACCOUNTADMIN TO USER somdutta;

---Create User SecurityAdmin ---
CREATE USER nitai password = '12345' DEFAULT_ROLE = SECURITYADMIN MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE SECURITYADMIN TO USER nitai;

---Create User SysAdmin ---
CREATE USER puja password = '12345' DEFAULT_ROLE = SYSADMIN MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE SYSADMIN TO USER puja;


--- Grant access to Warehouse --
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE USERADMIN;

-- Logged in as SecurityAdmin --

/*
Create four role

TEAM_LEAD (All privilege)
    DEVELOPER (DDL DML and Select privilege)
    TESTER (DML and Select privilege)
    PRODUCTION_SUPPORT (Select privilege)

*/

--- Creating Role ---
CREATE ROLE TEAM_LEAD;
CREATE ROLE DEVELOPER;
CREATE ROLE TESTER;
CREATE ROLE PRODUCTION_SUPPORT;


--- Creating Hierarchy ---
GRANT ROLE PRODUCTION_SUPPORT TO ROLE TESTER;
GRANT ROLE TESTER TO ROLE DEVELOPER;
GRANT ROLE DEVELOPER TO ROLE TEAM_LEAD;
GRANT ROLE TEAM_LEAD TO ROLE SYSADMIN;



---Create User PRODUCTION_SUPPORT ---
--- santu
--- sanjay
--- swarup
--- surojit

CREATE USER santu password = '12345' DEFAULT_ROLE = PRODUCTION_SUPPORT MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE PRODUCTION_SUPPORT TO USER santu;

CREATE USER sanjay password = '12345' DEFAULT_ROLE = PRODUCTION_SUPPORT MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE PRODUCTION_SUPPORT TO USER sanjay;

CREATE USER swarup password = '12345' DEFAULT_ROLE = PRODUCTION_SUPPORT MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE PRODUCTION_SUPPORT TO USER swarup;

CREATE USER surojit password = '12345' DEFAULT_ROLE = PRODUCTION_SUPPORT MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE PRODUCTION_SUPPORT TO USER surojit;


---Create User Tester ---
--- jina
--- goja
--- joydeep

CREATE USER jina password = '12345' DEFAULT_ROLE = TESTER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE TESTER TO USER jina;

CREATE USER goja password = '12345' DEFAULT_ROLE = TESTER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE TESTER TO USER goja;

CREATE USER joydeep password = '12345' DEFAULT_ROLE = TESTER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE TESTER TO USER joydeep;

---Create User DEVELOPER ---
--- ankit
--- pranshu

CREATE USER ankit password = '12345' DEFAULT_ROLE = DEVELOPER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE DEVELOPER TO USER ankit;

CREATE USER pranshu password = '12345' DEFAULT_ROLE = DEVELOPER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE DEVELOPER TO USER pranshu;

---Create User TEAM_LEAD ---
--- anik

CREATE USER anik password = '12345' DEFAULT_ROLE = TEAM_LEAD MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE TEAM_LEAD TO USER anik;


--- Creating Role ---
CREATE ROLE SENIOR_MANAGER;
CREATE ROLE MANAGER;

--- Creating Hierarchy ---
--- This time we are not assigning to SYSADMIN role ---
GRANT ROLE MANAGER TO ROLE SENIOR_MANAGER;

---Create User MANAGER ---
--- injamam
--- soumen

CREATE USER injamam password = '12345' DEFAULT_ROLE = MANAGER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE MANAGER TO USER injamam;

CREATE USER soumen password = '12345' DEFAULT_ROLE = MANAGER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE MANAGER TO USER soumen;


---Create User SENIOR_MANAGER ---
--- gourab

CREATE USER gourab password = '12345' DEFAULT_ROLE = SENIOR_MANAGER MUST_CHANGE_PASSWORD = TRUE; 
GRANT ROLE SENIOR_MANAGER TO USER gourab;


--- Logged in as SYSADMIN ---

--- Create a Warehouse with small size ---
CREATE OR REPLACE WAREHOUSE PUBLIC_WH
    WITH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

--- Grant to all user to access the Warehouse ---
GRANT USAGE ON WAREHOUSE PUBLIC_WH TO ROLE PUBLIC;

--- Create a database which is accessible to everyone ---
CREATE OR REPLACE DATABASE PUBLIC_DB;
GRANT USAGE ON DATABASE PUBLIC_DB TO ROLE PUBLIC;


--- Create a Project database ---
CREATE OR REPLACE DATABASE CREDIT_ANALYSIS_TOOL;
--- Grant ownership to TEAM_LEAD to we created using SECURITYADMIN ---
GRANT OWNERSHIP ON DATABASE CREDIT_ANALYSIS_TOOL TO ROLE TEAM_LEAD;
--- Now ownership of the database is TEAM_LEAD which is assign to SYSADMIN---
GRANT OWNERSHIP ON SCHEMA PUBLIC TO ROLE TEAM_LEAD;


--- Create another Project database ---
CREATE OR REPLACE DATABASE CREDIT_FINANCIAL;
--- Grant ownership to TEAM_LEAD to we created using SECURITYADMIN ---
GRANT OWNERSHIP ON DATABASE CREDIT_FINANCIAL TO ROLE SENIOR_MANAGER;
--- Now ownership of the database is TEAM_LEAD which is assign to SYSADMIN---
GRANT OWNERSHIP ON SCHEMA PUBLIC TO ROLE SENIOR_MANAGER;

--- Droping the database ---
DROP DATABASE CREDIT_FINANCIAL;
--- We can't drop because the Ownership got changed ---



















